/*
 * This file was generated by the Gradle 'init' task.
 */

rootProject.name = "TNML"
include(":TNML-CORE")
include(":TNML-Paper")
include(":TNML-Example")
include(":TNML-Folia")
include(":TNML-Bukkit")
include(":TNML-Sponge-API-8")
project(":TNML-CORE").projectDir = file("Core")
project(":TNML-Paper").projectDir = file("Paper")
project(":TNML-Example").projectDir = file("Examples")
project(":TNML-Folia").projectDir = file("Folia")
project(":TNML-Bukkit").projectDir = file("Bukkit")
project(":TNML-Sponge-API-8").projectDir = file("Sponge8")
