/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-conventions")
}

dependencies {
    api(libs.org.jetbrains.annotations)
    compileOnly(libs.net.tnemc.tnil.core)
}

description = "The New Menu Library Core"
