/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-conventions")
}

dependencies {
    api(project(":TNML-CORE"))
    api(project(":TNML-Bukkit"))
    compileOnly(libs.org.spigotmc.spigot.api)
    compileOnly(libs.net.tnemc.tnil.core)
    compileOnly(libs.net.tnemc.tnil.bukkit)
    compileOnly(libs.net.kyori.adventure.text.serializer.plain)
    compileOnly(libs.net.kyori.adventure.api)
    compileOnly(libs.net.kyori.adventure.text.serializer.json)
    compileOnly(libs.net.kyori.adventure.text.serializer.legacy)
}

description = "The New Menu Library Examples"
