name: 'TNML-Test'
version: '1.5.0.0'
description: 'Example Bukkit Plugin for TNML testing.'
authors: [ 'creatorfromhell' ]
website: 'https://github.com/TheNewEconomy/TNML'

main: 'net.tnemc.menu.example.bukkit.BukkitTNML'
api-version: '1.13'