/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-conventions")
}

dependencies {
    api(project(":TNML-CORE"))
    compileOnly(libs.org.spongepowered.spongeapi)
    compileOnly(libs.net.tnemc.tnil.core)
    compileOnly(libs.net.tnemc.tnil.sponge)
}

description = "The New Menu Library Sponge API-8"
