/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-conventions")
}

dependencies {
    api(project(":TNML-CORE"))
    compileOnly(libs.net.tnemc.tnil.core)
    compileOnly(libs.net.tnemc.tnil.bukkit)
    compileOnly(libs.org.spigotmc.spigot.api)
}

description = "The New Menu Library Bukkit"
