/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-conventions")
}

dependencies {
    api(project(":TNML-Paper"))
    compileOnly(libs.dev.folia.folia.api)
    compileOnly(libs.net.tnemc.tnil.core)
    compileOnly(libs.net.tnemc.tnil.paper)
}

description = "The New Menu Library Folia"
