/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-conventions")
}

dependencies {
    api(project(":TNML-CORE"))
    compileOnly(libs.io.papermc.paper.paper.api)
    compileOnly(libs.net.tnemc.tnil.core)
    compileOnly(libs.net.tnemc.tnil.paper)
}

description = "The New Menu Library Paper"
